# Generated by Django 3.1.2 on 2020-10-03 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('enlace', models.CharField(max_length=200)),
                ('edicion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paragrafo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.IntegerField()),
                ('paragrafo', models.CharField(max_length=50)),
                ('dialogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paragrafos', to='notes.dialogo')),
                ('personajes', models.ManyToManyField(related_name='apariciones', to='notes.Personaje')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renglon', models.IntegerField()),
                ('fecha', models.DateField(default=django.utils.timezone.now, null=True)),
                ('anotación', models.TextField()),
                ('anotador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anotaciones', to=settings.AUTH_USER_MODEL)),
                ('paragrafo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anotaciones', to='notes.paragrafo')),
            ],
        ),
    ]
