# Generated by Django 3.1.2 on 2020-10-03 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='anotación',
            new_name='anotacion',
        ),
    ]
